
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ include "instance.name" . }}
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "instance.name" . }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app.kubernetes.io/instance: {{ include "instance.name" . }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
          - name: {{ .Values.container.mount.name }}
            mountPath: {{ include "mount.path" . }}
          command: ["/bin/sh"]
          args: ["-c", {{ include "args" . | quote}} ]

      volumes:
      {{- toYaml .Values.container.volumes | nindent 6}}
