
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ID }}-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.org/websocket-services: "{{ .Release.Name }}-{{ .Values.ID }}-service"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/rewrites: "serviceName={{ .Release.Name }}-{{ .Values.ID }}-service rewrite=/"
spec:
  rules:
  - host: "michaelepps.me"
    http:
      paths:
      - path: /{{ .Release.Name }}-{{ .Values.ID }}
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.ID }}-service
          servicePort: "code-server"
