
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ID }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: "env.michaelepps.me"
    http:
      paths:
      - path: /{{ .Release.Name }}-{{ .Values.ID }}/(.*)
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.ID }}-service
          servicePort: "code-server"
