apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.ID }}-service
    labels: 
        app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.ID }}-service
        app.kubernetes.io/managed-by: helm
spec:
    selector:
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.ID }}
    ports: 
    - name: "code-server"
      port: 8443
      protocol: TCP
