apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.ID }}-service
    labels: 
        app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.ID }}-service
        app.kubernetes.io/managed-by: helm
spec:
    type: NodePort
    selector:
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.ID }}
    ports: 
    - port: 8443
      nodePort: 30001