instance: test
version: 0.0.1
ID: test

container:
  name: code-server
  image: linuxserver/code-server:latest
  port: 8443
  mount:
    name: data
    basePath: /usr/share/
  volumes:
    - name: data
      emptyDir: {}

ingress:
  host: env.michaelepps.me

extensions:
  - golang.go

runtimes:
  - name: go
    version: "1.15"
