apiVersion: v1
kind: Service
metadata:
    name: {{ include "instance.name" . }}-service
    labels: 
        app.kubernetes.io/name: {{ include "instance.name" . }}-service
        app.kubernetes.io/managed-by: helm
spec:
    selector:
        app.kubernetes.io/instance: {{ include "instance.name" . }}
    ports: 
    - port: {{ .Values.container.port }}
      protocol: TCP
