apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-service
    labels: 
        app.kubernetes.io/name: {{ .Release.Name }}-service
        app.kubernetes.io/managed-by: helm
spec:
    selector:
        app.kubernetes.io/instance: {{ .Release.Name }}-instance
    ports: 
    - port: {{ .Values.container.port }}
      protocol: TCP
